In [1]:
import numpy as np
import cv2
from tensorflow.keras import layers,models
from sklearn.model_selection import train_test_split
from tensorflow.keras.optimizers import Adam
import os

In [2]:
os.listdir(r"C:\Users\Manthan\Desktop\jupyter_extension_prettier\vs_code_extension\dog\Dog Segmentation")

['Images', 'Labels']

In [3]:

X = []
y = []

image_path = r"C:\Users\Manthan\Desktop\jupyter_extension_prettier\vs_code_extension\dog\Dog Segmentation\Images"
for i in os.listdir(image_path):
    img = cv2.imread(f"{image_path}/{i}", cv2.IMREAD_GRAYSCALE)
    if img is not None:
        img = cv2.resize(img, (128, 128))
        X.append(img)

label_path = r"C:\Users\Manthan\Desktop\jupyter_extension_prettier\vs_code_extension\dog\Dog Segmentation\Labels"
for i in os.listdir(label_path):
    img = cv2.imread(f"{label_path}/{i}", cv2.IMREAD_GRAYSCALE)
    if img is not None:
        img = cv2.resize(img, (128, 128))
        y.append(img)


In [4]:
X = np.array(X)/255.0
y = np.array(y)/255.0

print(X[0])
print(y[0])
print()
print(X.shape)
print(y.shape)

[[0.16862745 0.18431373 0.18823529 ... 0.35686275 0.40392157 0.39607843]
 [0.16470588 0.18039216 0.19607843 ... 0.31372549 0.42745098 0.38823529]
 [0.16078431 0.17647059 0.16862745 ... 0.45490196 0.44313725 0.38823529]
 ...
 [0.6        0.6745098  0.61568627 ... 0.47058824 0.51764706 0.56862745]
 [0.61568627 0.53333333 0.62352941 ... 0.42352941 0.38431373 0.46666667]
 [0.4627451  0.52941176 0.5254902  ... 0.49411765 0.4745098  0.49019608]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

(179, 128, 128)
(179, 128, 128)


In [5]:
X_train, y_train, X_test, y_test = train_test_split(X, y, test_size=0.2, random_state = 42)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)



(143, 128, 128)
(36, 128, 128)
(143, 128, 128)
(36, 128, 128)


In [6]:
model = models.Sequential([
    layers.Conv2D(8 ,(3,3), padding="same", activation="relu", input_shape=(128,128,1)),
    layers.Conv2D(8, (3, 3), activation="relu", padding="same"),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(16 ,(3,3), padding="same", activation="relu"),
    layers.Conv2D(16, (3, 3), activation="relu", padding="same"),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(32, (3, 3), activation="relu", padding="same"),
    layers.Conv2D(32, (3, 3), activation="relu", padding="same"),

    layers.Conv2DTranspose(16, (3,3), strides=(2,2), padding="same", activation="relu"),
    layers.Conv2D(16, (3, 3), activation="relu", padding="same"),
    layers.Conv2D(16, (3, 3), activation="relu", padding="same"),

    layers.Conv2DTranspose(8, (3,3), strides=(2,2), padding="same", activation="relu"),
    layers.Conv2D(8, (3, 3), activation="relu", padding="same"),
    layers.Conv2D(1, (1, 1), activation="sigmoid", padding="same"),
])

C:\Users\Manthan\.conda\envs\tf\lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [7]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 128, 128, 8)         │              80 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 128, 128, 8)         │             584 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 64, 64, 8)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_2 (Conv2D)                    │ (None, 64, 64, 16)          │           1,168 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_3 (Conv2D)                    │ (None, 64, 64, 16)          │           2,320 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 32, 32, 16)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_4 (Conv2D)                    │ (None, 32, 32, 32)          │           4,640 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_5 (Conv2D)                    │ (None, 32, 32, 32)          │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_transpose (Conv2DTranspose)   │ (None, 64, 64, 16)          │           4,624 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_6 (Conv2D)                    │ (None, 64, 64, 16)          │           2,320 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_7 (Conv2D)                    │ (None, 64, 64, 16)          │           2,320 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_transpose_1 (Conv2DTranspose) │ (None, 128, 128, 8)         │           1,160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_8 (Conv2D)                    │ (None, 128, 128, 8)         │             584 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_9 (Conv2D)                    │ (None, 128, 128, 1)         │               9 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 29,057 (113.50 KB)

 Trainable params: 29,057 (113.50 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer=Adam(learning_rate=0.01), 
              loss="binary_crossentropy", 
              metrics=["accuracy"])
model.fit(X_train, X_test, epochs=1001, batch_size=32, validation_data=(y_train, y_test))

Epoch 1/1001
5/5 ━━━━━━━━━━━━━━━━━━━━ 9s 476ms/step - accuracy: 0.5868 - loss: 0.6935 - val_accuracy: 0.5712 - val_loss: 0.6825
Epoch 2/1001
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 304ms/step - accuracy: 0.6072 - loss: 0.6721 - val_accuracy: 0.5712 - val_loss: 0.6880
Epoch 3/1001
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 304ms/step - accuracy: 0.6031 - loss: 0.6689 - val_accuracy: 0.5712 - val_loss: 0.6824
Epoch 4/1001
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 302ms/step - accuracy: 0.6224 - loss: 0.6519 - val_accuracy: 0.5712 - val_loss: 0.6639
Epoch 5/1001
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 295ms/step - accuracy: 0.5992 - loss: 0.6662 - val_accuracy: 0.5712 - val_loss: 0.6594
Epoch 6/1001
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 304ms/step - accuracy: 0.6098 - loss: 0.6485 - val_accuracy: 0.5712 - val_loss: 0.6641
Epoch 7/1001
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 310ms/step - accuracy: 0.6059 - loss: 0.6512 - val_accuracy: 0.5712 - val_loss: 0.6577
Epoch 8/1001
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 310ms/step - accuracy: 0.6073 - loss: 0.6418 - val_accuracy: 0.

In [ ]:
# sample pred
import matplotlib.pyplot as plt
predict = model.predict(y_train[11].reshape(1,128,128,1))
binary_mask = (predict > 0.5).astype(np.uint8)
binary_mask = binary_mask.reshape(128, 128)

plt.subplot(2,2,1)
plt.imshow(y_train[11], cmap="gray")
plt.subplot(2,2,2)
plt.imshow(binary_mask, cmap='gray')
plt.show()